version: '2'
services:
<<<<<<< HEAD
    jxjhipstermicroservicetemplate-app:
        image: jxjhipstermicroservicetemplate
=======
    MasternodesOnlineSupplementApi-app:
        image: MasternodesOnlineSupplementApi
>>>>>>> 0284cc9f6f3785d76bb0b3ca255ac2b96b28461d
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
<<<<<<< HEAD
            - SPRING_DATA_MONGODB_URI=mongodb://jxjhipstermicroservicetemplate-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=JxJhipsterMicroserviceTemplate
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_JEST_URI=http://jxjhipstermicroservicetemplate-elasticsearch:9200
    jxjhipstermicroservicetemplate-mongodb:
        extends:
            file: mongodb.yml
            service: jxjhipstermicroservicetemplate-mongodb
    jxjhipstermicroservicetemplate-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jxjhipstermicroservicetemplate-elasticsearch
=======
            - SPRING_DATA_MONGODB_URI=mongodb://MasternodesOnlineSupplementApi-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MasternodesOnlineSupplementApi
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_JEST_URI=http://MasternodesOnlineSupplementApi-elasticsearch:9200
    MasternodesOnlineSupplementApi-mongodb:
        extends:
            file: mongodb.yml
            service: MasternodesOnlineSupplementApi-mongodb
    MasternodesOnlineSupplementApi-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: MasternodesOnlineSupplementApi-elasticsearch
>>>>>>> 0284cc9f6f3785d76bb0b3ca255ac2b96b28461d
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
