version: '2'
services:
  masternodesonlinesupplementapi-mongodb:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/MasternodesOnlineSupplementApi/mongodb/:/data/db/
